import Head from "next/head";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

//** These below lines of code disabled the no-SSR rendering, to prevent the react-hydration error*/
import dynamic from "next/dynamic";
const ParentContainer = dynamic(() => import("../components/ParentContainer"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>zintools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/zintools-logo.jpg" />
      </Head>
      <main className={`${inter.className}`}>
        <ParentContainer />
      </main>
    </>
  );
}
